#pragma once
// chord_table.h is generated by T001 and lives at src/chord_table/chord_table.h
// The decoder wraps it with a lookup function.
#include "chord_table.h"  // CHORD_TABLE[], CHORD_TABLE_SIZE
#include <cstdint>
#include <cstddef>

// Returns the ASCII code for a given bitmask, or -1 if not found.
inline int chord_to_char(uint16_t bitmask) {
    for (size_t i = 0; i < CHORD_TABLE_SIZE; i++) {
        if (CHORD_TABLE[i].bitmask == bitmask) return CHORD_TABLE[i].ascii;
    }
    return -1;
}

// Returns the bitmask for a given ASCII code, or 0 if not found.
inline uint16_t char_to_chord(uint8_t ascii) {
    for (size_t i = 0; i < CHORD_TABLE_SIZE; i++) {
        if (CHORD_TABLE[i].ascii == ascii) return CHORD_TABLE[i].bitmask;
    }
    return 0;
}
